# Generated by Django 3.2.6 on 2021-08-26 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_administration', '0002_deposit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='Factory',
        ),
    ]
