# Generated by Django 3.2.6 on 2021-08-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
