# Generated by Django 3.2.6 on 2021-08-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210826_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
        migrations.DeleteModel(
            name='CategoryType',
        ),
    ]
