# Generated by Django 3.2.6 on 2021-08-27 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210827_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryrelations',
            old_name='category_id',
            new_name='category',
        ),
    ]
