# Generated by Django 3.2.6 on 2021-08-27 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210827_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryrelations',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_to_category', to='products.category'),
        ),
        migrations.AlterField(
            model_name='categoryrelations',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_to_parent', to='products.category'),
        ),
        migrations.CreateModel(
            name='ProductLocalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.SmallIntegerField(null=True)),
                ('value', models.TextField()),
                ('column_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productlocalizationcolumns')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
